// codegen/c_backend.cpp
// Lifts PowerPC Gekko/Broadway instructions to C code.
#include "c_backend.h"
#include "instructions.h"
#include <cstdio>
#include <algorithm>

// ============================================================
// Helper macros used in the generated-C snippets
// ============================================================
// These macros expand to C expressions referencing `s` (the PPCState*).
#define GPR(n)    "s->gpr[" #n "]"
// We use snprintf formatting instead; see helpers below.

static std::string gpr(u32 n) {
    char b[32]; snprintf(b, sizeof(b), "s->gpr[%u]", n); return b;
}
static std::string fpr_d(u32 n) {
    char b[32]; snprintf(b, sizeof(b), "s->fpr[%u].as_f64", n); return b;
}
static std::string fpr_s(u32 n) {   // single precision slot
    char b[32]; snprintf(b, sizeof(b), "s->fpr[%u].ps0", n); return b;
}

// Format a signed immediate as a C cast
static std::string simm(s32 v) {
    char b[32]; snprintf(b, sizeof(b), "((s32)0x%x)", v); return b;
}
static std::string uimm(u32 v) {
    char b[32]; snprintf(b, sizeof(b), "0x%xu", v); return b;
}

// ============================================================
// Top-level emit
// ============================================================
std::string CBackend::emit_translation_unit(
    const std::map<u32, Function>& functions,
    const std::string& module_name)
{
    std::ostringstream out;
    out << "// Auto-generated by ppc-recompiler — DO NOT EDIT\n";
    out << "// Module: " << module_name << "\n\n";
    out << "#include <stdint.h>\n";
    out << "#include <math.h>\n";
    out << "#include \"" << m_cfg.runtime_header << "\"\n\n";

    // Forward declarations
    out << "/* Forward declarations */\n";
    for (const auto& [addr, fn] : functions)
        out << "static " << fn_proto(fn) << ";\n";
    out << "\n";

    // Emit each function
    for (const auto& [addr, fn] : functions) {
        if (fn.blocks.empty()) continue;
        out << emit_function(fn) << "\n";
    }
    return out.str();
}

std::string CBackend::emit_function(const Function& fn) {
    std::ostringstream out;
    out << "static " << fn_proto(fn) << " {\n";

    if (fn.blocks.empty()) {
        out << "  /* empty */\n}\n";
        return out.str();
    }

    // Local variable for early exit flag (indirect branches)
    out << "  u32 _ctr_target;\n";
    out << "  goto " << block_label(fn.entry_addr) << ";\n\n";

    // Emit blocks in address order
    std::vector<u32> addrs;
    for (const auto& [a, _] : fn.blocks) addrs.push_back(a);
    std::sort(addrs.begin(), addrs.end());

    for (u32 addr : addrs) {
        emit_block(out, fn.blocks.at(addr), fn);
    }

    out << "  _fn_return:\n  return;\n";
    out << "}\n";
    return out.str();
}

void CBackend::emit_block(std::ostringstream& out, const BasicBlock& bb, const Function& fn) {
    out << "  " << block_label(bb.start_addr) << ":;\n";

    for (size_t i = 0; i < bb.instructions.size(); i++) {
        const DecodedInstr& d = bb.instructions[i];

        if (m_cfg.emit_comments) {
            out << "  /* 0x" << std::hex << d.address << std::dec
                << "  " << ppc_disasm(d) << " */\n";
        }

        if (m_cfg.emit_pc_updates)
            out << "  s->pc = 0x" << std::hex << d.address << std::dec << "u;\n";

        if (m_cfg.emit_cycle_count)
            out << "  s->cycle_count++;\n";

        std::string code = emit_instr(d);
        if (!code.empty())
            out << "  " << code << "\n";
    }

    // Emit block terminator
    if (bb.ends_with_blr) {
        out << "  goto _fn_return;\n\n";
    }
    else if (bb.ends_with_indirect) {
        out << "  /* indirect branch – return to dispatcher */\n";
        out << "  goto _fn_return;\n\n";
    }
    else if (!bb.successors.empty()) {
        // Explicit jump to successors (already handled in branch instructions)
        // If the last instruction wasn't a branch (e.g. block split mid-block),
        // emit a fallthrough.
        const DecodedInstr& last = bb.instructions.back();
        if (!last.is_branch) {
            out << "  goto " << block_label(bb.successors[0]) << ";\n\n";
        }
        else {
            out << "\n";
        }
    }
    else {
        out << "  goto _fn_return;\n\n";
    }
}

// ============================================================
// Per-instruction dispatch
// ============================================================
std::string CBackend::emit_instr(const DecodedInstr& d) {
    switch (d.iclass) {
    case PPCInstrClass::INTEGER:    return emit_integer(d);
    case PPCInstrClass::BRANCH:     return emit_branch(d, d.address + 4);
    case PPCInstrClass::LOADSTORE:  return emit_loadstore(d);
    case PPCInstrClass::FLOAT:      return emit_float(d);
    case PPCInstrClass::SYSTEM:     return emit_system(d);
    case PPCInstrClass::PAIRED_SINGLE: return emit_ps(d);
    default:
        return "rt_unimplemented(s, 0x" + [&] { char b[16];
        snprintf(b, sizeof(b), "%08xu", d.address); return std::string(b); }()
            + ", 0x" + [&] { char b[16];
        snprintf(b, sizeof(b), "%08xu", d.raw.hex); return std::string(b); }() + ");";
    }
}

// ============================================================
// Integer ALU
// ============================================================
std::string CBackend::emit_integer(const DecodedInstr& d) {
    const auto& I = d.raw;
    char buf[512];
    u32 op = I.OPCD;
    std::string RD = gpr(I.RD), RA = gpr(I.RA), RB = gpr(I.RB), RS = gpr(I.RS);
    s32 imm = (s32)(s16)I.SIMM_16;

    // ---- Immediate forms ----
    if (op == 14) { // addi
        if (I.RA == 0)
            snprintf(buf, sizeof(buf), "%s = (s32)0x%x;", RD.c_str(), imm);
        else
            snprintf(buf, sizeof(buf), "%s = %s + (s32)%d;", RD.c_str(), RA.c_str(), imm);
        return buf;
    }
    if (op == 15) { // addis
        u32 val = (u32)imm << 16;
        if (I.RA == 0)
            snprintf(buf, sizeof(buf), "%s = 0x%xu;", RD.c_str(), val);
        else
            snprintf(buf, sizeof(buf), "%s = %s + 0x%xu;", RD.c_str(), RA.c_str(), val);
        return buf;
    }
    if (op == 7) { // mulli
        snprintf(buf, sizeof(buf), "%s = (s32)%s * (s32)%d;", RD.c_str(), RA.c_str(), imm);
        return buf;
    }
    if (op == 8) { // subfic
        snprintf(buf, sizeof(buf), "{ u64 _r = (u64)(s32)%d - (u64)%s; %s = (u32)_r; xer_set_ca(s, (_r>>32)&1); }",
            imm, RA.c_str(), RD.c_str());
        return buf;
    }
    if (op == 12) { // addic
        snprintf(buf, sizeof(buf), "{ u64 _r = (u64)%s + (u64)(s32)%d; %s = (u32)_r; xer_set_ca(s,(_r>>32)&1); }",
            RA.c_str(), imm, RD.c_str());
        return buf;
    }
    if (op == 13) { // addic.
        snprintf(buf, sizeof(buf), "{ u64 _r = (u64)%s + (u64)(s32)%d; %s = (u32)_r; xer_set_ca(s,(_r>>32)&1); cmp_set_cr0(s,(s32)%s,0); }",
            RA.c_str(), imm, RD.c_str(), RD.c_str());
        return buf;
    }
    if (op == 24) { // ori
        if (I.RS == 0 && I.RA == 0 && I.UIMM == 0) return "/* nop */";
        snprintf(buf, sizeof(buf), "%s = %s | 0x%xu;", RA.c_str(), RS.c_str(), I.UIMM);
        return buf;
    }
    if (op == 25) { // oris
        snprintf(buf, sizeof(buf), "%s = %s | 0x%xu;", RA.c_str(), RS.c_str(), I.UIMM << 16);
        return buf;
    }
    if (op == 26) { // xori
        snprintf(buf, sizeof(buf), "%s = %s ^ 0x%xu;", RA.c_str(), RS.c_str(), I.UIMM);
        return buf;
    }
    if (op == 27) { // xoris
        snprintf(buf, sizeof(buf), "%s = %s ^ 0x%xu;", RA.c_str(), RS.c_str(), I.UIMM << 16);
        return buf;
    }
    if (op == 28) { // andi.
        snprintf(buf, sizeof(buf), "%s = %s & 0x%xu; cmp_set_cr0(s,(s32)%s,0);",
            RA.c_str(), RS.c_str(), I.UIMM, RA.c_str());
        return buf;
    }
    if (op == 29) { // andis.
        snprintf(buf, sizeof(buf), "%s = %s & 0x%xu; cmp_set_cr0(s,(s32)%s,0);",
            RA.c_str(), RS.c_str(), I.UIMM << 16, RA.c_str());
        return buf;
    }
    if (op == 10) { // cmpli
        snprintf(buf, sizeof(buf), "{ int _lt=%s<0x%xu,_gt=%s>0x%xu,_eq=%s==0x%xu; cr_set_field(s,%u,_lt,_gt,_eq,s->xer.SO); }",
            RA.c_str(), I.UIMM, RA.c_str(), I.UIMM, RA.c_str(), I.UIMM, I.CRFD);
        return buf;
    }
    if (op == 11) { // cmpi
        snprintf(buf, sizeof(buf), "{ int _lt=(s32)%s<%d,_gt=(s32)%s>%d,_eq=(s32)%s==%d; cr_set_field(s,%u,_lt,_gt,_eq,s->xer.SO); }",
            RA.c_str(), imm, RA.c_str(), imm, RA.c_str(), imm, I.CRFD);
        return buf;
    }
    // Rotate/shift
    if (op == 20) { // rlwimi
        snprintf(buf, sizeof(buf), "{ u32 _m = ((0xFFFFFFFFu>>%u)<<(32-%u-%u+%u))>>(32-%u-%u); %s = (%s & ~_m) | (rotl32(%s,%u) & _m);%s }",
            I.MB, I.MB, I.ME, I.MB, I.MB, I.ME,
            RA.c_str(), RA.c_str(), RS.c_str(), I.SH,
            I.Rc_3 ? (" cmp_set_cr0(s,(s32)" + RA + ",0);").c_str() : "");
        return buf;
    }
    if (op == 21) { // rlwinm
        snprintf(buf, sizeof(buf), "{ u32 _r=rotl32(%s,%u); u32 _m=((0xFFFFFFFFu>>%u)&~((0xFFFFFFFFu>>(%u+1))>>1)); %s = _r & _m;%s }",
            RS.c_str(), I.SH, I.MB, I.ME, RA.c_str(),
            I.Rc_3 ? (" cmp_set_cr0(s,(s32)" + RA + ",0);").c_str() : "");
        return buf;
    }
    if (op == 23) { // rlwnm
        snprintf(buf, sizeof(buf), "{ u32 _r=rotl32(%s,%s&31); u32 _m=((0xFFFFFFFFu>>%u)&~((0xFFFFFFFFu>>(%u+1))>>1)); %s = _r & _m;%s }",
            RS.c_str(), RB.c_str(), I.MB, I.ME, RA.c_str(),
            I.Rc_3 ? (" cmp_set_cr0(s,(s32)" + RA + ",0);").c_str() : "");
        return buf;
    }

    // ---- Register-register (opcode 31) ----
    if (op == 31) {
        u32 xop = I.SUBOP10;
        bool rc = I.Rc;
        std::string rc_s = rc ? (" cmp_set_cr0(s,(s32)" + RA + ",0);") : "";

        switch (xop) {
        case 0: // cmp
            snprintf(buf, sizeof(buf), "{ int _l=(s32)%s<(s32)%s,_g=(s32)%s>(s32)%s,_e=%s==%s; cr_set_field(s,%u,_l,_g,_e,s->xer.SO); }",
                RA.c_str(), RB.c_str(), RA.c_str(), RB.c_str(), RA.c_str(), RB.c_str(), I.CRFD);
            return buf;
        case 32: // cmpl
            snprintf(buf, sizeof(buf), "{ int _l=%s<%s,_g=%s>%s,_e=%s==%s; cr_set_field(s,%u,_l,_g,_e,s->xer.SO); }",
                RA.c_str(), RB.c_str(), RA.c_str(), RB.c_str(), RA.c_str(), RB.c_str(), I.CRFD);
            return buf;
        case 8: // subfc (RD = ~RA + RB + 1)
            snprintf(buf, sizeof(buf), "{ u64 _r=(u64)%s+(u64)~%s+1; %s=(u32)_r; xer_set_ca(s,(_r>>32)&1);%s }",
                RB.c_str(), RA.c_str(), RD.c_str(), rc ? (" cmp_set_cr0(s,(s32)" + RD + ",0);").c_str() : "");
            return buf;
        case 40: // subf
            snprintf(buf, sizeof(buf), "%s = %s - %s;%s", RD.c_str(), RB.c_str(), RA.c_str(),
                rc ? (" cmp_set_cr0(s,(s32)" + RD + ",0);").c_str() : "");
            return buf;
        case 10: // addc
            snprintf(buf, sizeof(buf), "{ u64 _r=(u64)%s+(u64)%s; %s=(u32)_r; xer_set_ca(s,(_r>>32)&1);%s }",
                RA.c_str(), RB.c_str(), RD.c_str(), rc ? (" cmp_set_cr0(s,(s32)" + RD + ",0);").c_str() : "");
            return buf;
        case 266: // add
            snprintf(buf, sizeof(buf), "%s = %s + %s;%s", RD.c_str(), RA.c_str(), RB.c_str(),
                rc ? (" cmp_set_cr0(s,(s32)" + RD + ",0);").c_str() : "");
            return buf;
        case 138: // adde
            snprintf(buf, sizeof(buf), "{ u64 _r=(u64)%s+(u64)%s+s->xer.CA; %s=(u32)_r; xer_set_ca(s,(_r>>32)&1);%s }",
                RA.c_str(), RB.c_str(), RD.c_str(), rc ? (" cmp_set_cr0(s,(s32)" + RD + ",0);").c_str() : "");
            return buf;
        case 202: // addze: rD = rA + 0 + CA
            snprintf(buf, sizeof(buf), "{ u64 _r=(u64)%s+s->xer.CA; %s=(u32)_r; xer_set_ca(s,(_r>>32)&1);%s }",
                RA.c_str(), RD.c_str(), rc ? (" cmp_set_cr0(s,(s32)" + RD + ",0);").c_str() : "");
            return buf;
        case 200: // subfze: rD = ~rA + 0 + CA
            snprintf(buf, sizeof(buf), "{ u64 _r=(u64)~%s+(u64)s->xer.CA; %s=(u32)_r; xer_set_ca(s,(_r>>32)&1);%s }",
                RA.c_str(), RD.c_str(), rc ? (" cmp_set_cr0(s,(s32)" + RD + ",0);").c_str() : "");
            return buf;
        case 234: // addme: rD = rA + (-1) + CA  (= rA + 0xFFFFFFFF + CA)
            snprintf(buf, sizeof(buf), "{ u64 _r=(u64)%s+0xFFFFFFFFull+(u64)s->xer.CA; %s=(u32)_r; xer_set_ca(s,(_r>>32)&1);%s }",
                RA.c_str(), RD.c_str(), rc ? (" cmp_set_cr0(s,(s32)" + RD + ",0);").c_str() : "");
            return buf;
        case 232: // subfme: rD = ~rA + (-1) + CA
            snprintf(buf, sizeof(buf), "{ u64 _r=(u64)~%s+0xFFFFFFFFull+(u64)s->xer.CA; %s=(u32)_r; xer_set_ca(s,(_r>>32)&1);%s }",
                RA.c_str(), RD.c_str(), rc ? (" cmp_set_cr0(s,(s32)" + RD + ",0);").c_str() : "");
            return buf;
        case 104: // neg
            snprintf(buf, sizeof(buf), "%s = -(s32)%s;%s", RD.c_str(), RA.c_str(),
                rc ? (" cmp_set_cr0(s,(s32)" + RD + ",0);").c_str() : "");
            return buf;
        case 235: // mullw
            snprintf(buf, sizeof(buf), "%s = (u32)((s32)%s * (s32)%s);%s",
                RD.c_str(), RA.c_str(), RB.c_str(), rc ? (" cmp_set_cr0(s,(s32)" + RD + ",0);").c_str() : "");
            return buf;
        case 11: // mulhwu
            snprintf(buf, sizeof(buf), "%s = (u32)(((u64)%s*(u64)%s)>>32);%s",
                RD.c_str(), RA.c_str(), RB.c_str(), rc ? (" cmp_set_cr0(s,(s32)" + RD + ",0);").c_str() : "");
            return buf;
        case 75: // mulhw
            snprintf(buf, sizeof(buf), "%s = (u32)(((s64)(s32)%s*(s64)(s32)%s)>>32);%s",
                RD.c_str(), RA.c_str(), RB.c_str(), rc ? (" cmp_set_cr0(s,(s32)" + RD + ",0);").c_str() : "");
            return buf;
        case 491: // divw
            snprintf(buf, sizeof(buf), "%s = (%s!=0) ? (u32)((s32)%s/(s32)%s) : 0;%s",
                RD.c_str(), RB.c_str(), RA.c_str(), RB.c_str(), rc ? (" cmp_set_cr0(s,(s32)" + RD + ",0);").c_str() : "");
            return buf;
        case 459: // divwu
            snprintf(buf, sizeof(buf), "%s = (%s!=0) ? %s/%s : 0;%s",
                RD.c_str(), RB.c_str(), RA.c_str(), RB.c_str(), rc ? (" cmp_set_cr0(s,(s32)" + RD + ",0);").c_str() : "");
            return buf;
        case 28: // and
            snprintf(buf, sizeof(buf), "%s = %s & %s;%s", RA.c_str(), RS.c_str(), RB.c_str(), rc_s.c_str()); return buf;
        case 60: // andc
            snprintf(buf, sizeof(buf), "%s = %s & ~%s;%s", RA.c_str(), RS.c_str(), RB.c_str(), rc_s.c_str()); return buf;
        case 444: // or
            snprintf(buf, sizeof(buf), "%s = %s | %s;%s", RA.c_str(), RS.c_str(), RB.c_str(), rc_s.c_str()); return buf;
        case 412: // orc
            snprintf(buf, sizeof(buf), "%s = %s | ~%s;%s", RA.c_str(), RS.c_str(), RB.c_str(), rc_s.c_str()); return buf;
        case 316: // xor
            snprintf(buf, sizeof(buf), "%s = %s ^ %s;%s", RA.c_str(), RS.c_str(), RB.c_str(), rc_s.c_str()); return buf;
        case 124: // nor
            snprintf(buf, sizeof(buf), "%s = ~(%s | %s);%s", RA.c_str(), RS.c_str(), RB.c_str(), rc_s.c_str()); return buf;
        case 284: // eqv
            snprintf(buf, sizeof(buf), "%s = ~(%s ^ %s);%s", RA.c_str(), RS.c_str(), RB.c_str(), rc_s.c_str()); return buf;
        case 476: // nand
            snprintf(buf, sizeof(buf), "%s = ~(%s & %s);%s", RA.c_str(), RS.c_str(), RB.c_str(), rc_s.c_str()); return buf;
        case 24: // slw
            snprintf(buf, sizeof(buf), "%s = (%s<32)?(%s<<(%s&31)):0;%s", RA.c_str(), RB.c_str(), RS.c_str(), RB.c_str(), rc_s.c_str()); return buf;
        case 536: // srw
            snprintf(buf, sizeof(buf), "%s = (%s<32)?(%s>>(%s&31)):0;%s", RA.c_str(), RB.c_str(), RS.c_str(), RB.c_str(), rc_s.c_str()); return buf;
        case 792: // sraw
            snprintf(buf, sizeof(buf), "{ u32 _n=%s&63; if(_n>=32){%s=(s32)%s>>31;xer_set_ca(s,((s32)%s<0));} else {%s=(s32)%s>>_n; xer_set_ca(s,((s32)%s<0)&&(%s<<(32-_n))!=0);}%s }",
                RB.c_str(), RA.c_str(), RS.c_str(), RS.c_str(), RA.c_str(), RS.c_str(), RS.c_str(), RS.c_str(), rc_s.c_str());
            return buf;
        case 824: // srawi
            snprintf(buf, sizeof(buf), "{ %s=(s32)%s>>%u; xer_set_ca(s,((s32)%s<0)&&((%s<<%u)!=0));%s }",
                RA.c_str(), RS.c_str(), I.SH, RS.c_str(), RS.c_str(), (32 - I.SH), rc_s.c_str());
            return buf;
        case 26: // cntlzw
            snprintf(buf, sizeof(buf), "%s = %s ? __builtin_clz(%s) : 32;%s", RA.c_str(), RS.c_str(), RS.c_str(), rc_s.c_str()); return buf;
        case 922: // extsh
            snprintf(buf, sizeof(buf), "%s = (u32)(s32)(s16)%s;%s", RA.c_str(), RS.c_str(), rc_s.c_str()); return buf;
        case 954: // extsb
            snprintf(buf, sizeof(buf), "%s = (u32)(s32)(s8)%s;%s", RA.c_str(), RS.c_str(), rc_s.c_str()); return buf;
        case 19: // mfcr
            snprintf(buf, sizeof(buf), "%s = s->cr.hex;", RD.c_str()); return buf;
        case 144: // mtcrf
            snprintf(buf, sizeof(buf), "{ u32 _mask=0; for(int _i=0;_i<8;_i++) if((%u>>_i)&1) _mask|=(0xFu<<(_i*4)); s->cr.hex=(_mask&%s)|(~_mask&s->cr.hex); }",
                I.CRFD, RS.c_str());
            return buf;
        case 339: // mfspr
            switch (I.SPR()) {
            case 8:  snprintf(buf, sizeof(buf), "%s = s->lr;", RD.c_str()); return buf;
            case 9:  snprintf(buf, sizeof(buf), "%s = s->ctr;", RD.c_str()); return buf;
            case 1:  snprintf(buf, sizeof(buf), "%s = s->xer.hex;", RD.c_str()); return buf;
            case 26: snprintf(buf, sizeof(buf), "%s = s->srr0;", RD.c_str()); return buf;
            case 27: snprintf(buf, sizeof(buf), "%s = s->srr1;", RD.c_str()); return buf;
            default: snprintf(buf, sizeof(buf), "/* mfspr %u -> %s */", I.SPR(), RD.c_str()); return buf;
            }
        case 467: // mtspr
            switch (I.SPR()) {
            case 8:  snprintf(buf, sizeof(buf), "s->lr  = %s;", RS.c_str()); return buf;
            case 9:  snprintf(buf, sizeof(buf), "s->ctr = %s;", RS.c_str()); return buf;
            case 1:  snprintf(buf, sizeof(buf), "s->xer.hex = %s;", RS.c_str()); return buf;
            case 26: snprintf(buf, sizeof(buf), "s->srr0 = %s;", RS.c_str()); return buf;
            case 27: snprintf(buf, sizeof(buf), "s->srr1 = %s;", RS.c_str()); return buf;
            default: snprintf(buf, sizeof(buf), "/* mtspr %u = %s */", I.SPR(), RS.c_str()); return buf;
            }
        default:
            snprintf(buf, sizeof(buf), "rt_unimplemented(s,0x%xu,0x%xu); /* %s */",
                d.address, d.raw.hex, d.mnemonic.c_str());
            return buf;
        }
    }

    // Condition register logical (opcode 19)
    // For CR-bit instructions the 5-bit operand fields map to X-form layout:
    //   crbD = bits 21-25 = I.RD,  crbA = bits 16-20 = I.RA,  crbB = bits 11-15 = I.RB
    if (op == 19) {
        u32 xop = I.XO;
        u32 crd = I.RD, cra = I.RA, crb = I.RB;
        switch (xop) {
        case 33:  // crnor:  crbD = ~(crbA | crbB)
            snprintf(buf, sizeof(buf),
                "{ int _r=!(cr_get_bit(s,%u)|cr_get_bit(s,%u)); cr_set_bit(s,%u,_r); }",
                cra, crb, crd); return buf;
        case 129: // crandc: crbD = crbA & ~crbB
            snprintf(buf, sizeof(buf),
                "{ int _r=cr_get_bit(s,%u)&!cr_get_bit(s,%u); cr_set_bit(s,%u,_r); }",
                cra, crb, crd); return buf;
        case 193: // crxor:  crbD = crbA ^ crbB
            snprintf(buf, sizeof(buf),
                "{ int _r=cr_get_bit(s,%u)^cr_get_bit(s,%u); cr_set_bit(s,%u,_r); }",
                cra, crb, crd); return buf;
        case 225: // crnand: crbD = ~(crbA & crbB)
            snprintf(buf, sizeof(buf),
                "{ int _r=!(cr_get_bit(s,%u)&cr_get_bit(s,%u)); cr_set_bit(s,%u,_r); }",
                cra, crb, crd); return buf;
        case 257: // crand:  crbD = crbA & crbB
            snprintf(buf, sizeof(buf),
                "{ int _r=cr_get_bit(s,%u)&cr_get_bit(s,%u); cr_set_bit(s,%u,_r); }",
                cra, crb, crd); return buf;
        case 289: // creqv:  crbD = ~(crbA ^ crbB)
            snprintf(buf, sizeof(buf),
                "{ int _r=!(cr_get_bit(s,%u)^cr_get_bit(s,%u)); cr_set_bit(s,%u,_r); }",
                cra, crb, crd); return buf;
        case 417: // crorc:  crbD = crbA | ~crbB
            snprintf(buf, sizeof(buf),
                "{ int _r=cr_get_bit(s,%u)|!cr_get_bit(s,%u); cr_set_bit(s,%u,_r); }",
                cra, crb, crd); return buf;
        case 449: // cror:   crbD = crbA | crbB
            snprintf(buf, sizeof(buf),
                "{ int _r=cr_get_bit(s,%u)|cr_get_bit(s,%u); cr_set_bit(s,%u,_r); }",
                cra, crb, crd); return buf;
        case 0:   // mcrf: copy CR field CRFS -> CRFD
            snprintf(buf, sizeof(buf),
                "{ u32 _f=cr_get_field(s,%u); cr_set_field(s,%u,"
                "(_f>>3)&1,(_f>>2)&1,(_f>>1)&1,_f&1); }",
                I.CRFS, I.CRFD); return buf;
        default:  return "";
        }
    }

    return "/* " + d.mnemonic + " (unlifted) */";
}

// ============================================================
// Branch instructions
// ============================================================
std::string CBackend::emit_branch(const DecodedInstr& d, u32 next_pc) {
    char buf[512];
    const auto& I = d.raw;
    u32 op = I.OPCD;

    if (op == 18) { // bx
        if (I.LK)
            snprintf(buf, sizeof(buf), "s->lr = 0x%xu;", next_pc);
        else
            buf[0] = 0;

        if (d.branch_target != UINT32_MAX) {
            // Direct branch – emit goto (same function) or call (different function)
            char label[64];
            snprintf(label, sizeof(label), " goto bb_%08x;", d.branch_target);
            return std::string(buf) + (buf[0] ? " " : "") + label;
        }
        else {
            return std::string(buf) + " /* indirect bx */ goto _fn_return;";
        }
    }

    if (op == 16) { // bcx
        std::string cond;
        u32 BO = I.BO, BI = I.BI;
        // Decode BO field per PowerPC ISA
        bool ctr_ok_always = (BO >> 2) & 1;
        bool ctr_zero = (BO >> 1) & 1;
        bool cond_ok_always = (BO >> 4) & 1;
        bool cond_true = (BO >> 3) & 1;

        std::string terms;
        if (!ctr_ok_always) {
            char ct[64];
            if (ctr_zero)
                snprintf(ct, sizeof(ct), "(--s->ctr == 0)");
            else
                snprintf(ct, sizeof(ct), "(--s->ctr != 0)");
            terms += ct;
        }
        if (!cond_ok_always) {
            char cc[64];
            snprintf(cc, sizeof(cc), "%s(cr_get_bit(s,%u))", cond_true ? "" : "!", BI);
            if (!terms.empty()) terms += " && ";
            terms += cc;
        }
        if (terms.empty()) terms = "1"; // unconditional

        std::string link_str;
        if (I.LK_2) { char lb[32]; snprintf(lb, sizeof(lb), "s->lr=0x%xu; ", next_pc); link_str = lb; }

        if (d.branch_target != UINT32_MAX) {
            snprintf(buf, sizeof(buf), "if(%s){ %sgoto bb_%08x; }",
                terms.c_str(), link_str.c_str(), d.branch_target);
        }
        else {
            snprintf(buf, sizeof(buf), "if(%s){ %s/* indirect */ goto _fn_return; }",
                terms.c_str(), link_str.c_str());
        }
        return buf;
    }

    if (op == 19) {
        u32 xop = I.XO;
        if (xop == 16) { // bclrx
            u32 BO = I.BO_2;
            bool ctr_ok_always = (BO >> 2) & 1;
            bool ctr_zero = (BO >> 1) & 1;
            bool cond_ok_always = (BO >> 4) & 1;
            bool cond_true = (BO >> 3) & 1;
            std::string terms;
            if (!ctr_ok_always) {
                terms += ctr_zero ? "(--s->ctr==0)" : "(--s->ctr!=0)";
            }
            if (!cond_ok_always) {
                if (!terms.empty()) terms += " && ";
                char cc[64]; snprintf(cc, sizeof(cc), "%s(cr_get_bit(s,%u))",
                    cond_true ? "" : "!", I.BI_2); terms += cc;
            }
            if (terms.empty()) terms = "1";
            if (I.LK_3)
                snprintf(buf, sizeof(buf), "if(%s){ s->lr=0x%xu; goto _fn_return; }",
                    terms.c_str(), next_pc);
            else
                snprintf(buf, sizeof(buf), "if(%s){ goto _fn_return; }", terms.c_str());
            return buf;
        }
        if (xop == 528) { // bcctrx
            if (I.LK_3)
                snprintf(buf, sizeof(buf), "s->lr=0x%xu; goto _fn_return; /* bcctr */", next_pc);
            else
                snprintf(buf, sizeof(buf), "goto _fn_return; /* bcctr */");
            return buf;
        }
    }
    return "/* unhandled branch */";
}

// ============================================================
// Load / Store
// ============================================================
std::string CBackend::emit_loadstore(const DecodedInstr& d) {
    char buf[512];
    const auto& I = d.raw;
    u32 op = I.OPCD;
    std::string RD = gpr(I.RD), RA = gpr(I.RA), RB = gpr(I.RB), RS = gpr(I.RS);
    s32 imm = (s32)(s16)I.SIMM_16;

    auto ea_d = [&]() -> std::string { // D-form EA
        char b[64];
        if (I.RA == 0) snprintf(b, sizeof(b), "(u32)(s32)%d", imm);
        else           snprintf(b, sizeof(b), "%s+(s32)%d", RA.c_str(), imm);
        return b;
        };
    auto ea_x = [&]() -> std::string { // X-form EA
        char b[64];
        if (I.RA == 0) snprintf(b, sizeof(b), "%s", RB.c_str());
        else           snprintf(b, sizeof(b), "%s+%s", RA.c_str(), RB.c_str());
        return b;
        };

    switch (op) {
    case 32: snprintf(buf, sizeof(buf), "%s = mem_read32(s,%s);", RD.c_str(), ea_d().c_str()); return buf;
    case 33: snprintf(buf, sizeof(buf), "%s = mem_read32(s,%s); %s = %s+(s32)%d;", RD.c_str(), ea_d().c_str(), RA.c_str(), RA.c_str(), imm); return buf;
    case 34: snprintf(buf, sizeof(buf), "%s = mem_read8(s,%s);", RD.c_str(), ea_d().c_str()); return buf;
    case 35: snprintf(buf, sizeof(buf), "%s = mem_read8(s,%s); %s = %s+(s32)%d;", RD.c_str(), ea_d().c_str(), RA.c_str(), RA.c_str(), imm); return buf;
    case 36: snprintf(buf, sizeof(buf), "mem_write32(s,%s,%s);", ea_d().c_str(), RS.c_str()); return buf;
    case 37: snprintf(buf, sizeof(buf), "mem_write32(s,%s,%s); %s = %s+(s32)%d;", ea_d().c_str(), RS.c_str(), RA.c_str(), RA.c_str(), imm); return buf;
    case 38: snprintf(buf, sizeof(buf), "mem_write8(s,%s,(u8)%s);", ea_d().c_str(), RS.c_str()); return buf;
    case 39: snprintf(buf, sizeof(buf), "mem_write8(s,%s,(u8)%s); %s = %s+(s32)%d;", ea_d().c_str(), RS.c_str(), RA.c_str(), RA.c_str(), imm); return buf;
    case 40: snprintf(buf, sizeof(buf), "%s = mem_read16(s,%s);", RD.c_str(), ea_d().c_str()); return buf;
    case 41: snprintf(buf, sizeof(buf), "%s = mem_read16(s,%s); %s = %s+(s32)%d;", RD.c_str(), ea_d().c_str(), RA.c_str(), RA.c_str(), imm); return buf;
    case 42: snprintf(buf, sizeof(buf), "%s = (u32)(s32)(s16)mem_read16(s,%s);", RD.c_str(), ea_d().c_str()); return buf;
    case 43: snprintf(buf, sizeof(buf), "%s = (u32)(s32)(s16)mem_read16(s,%s); %s = %s+(s32)%d;", RD.c_str(), ea_d().c_str(), RA.c_str(), RA.c_str(), imm); return buf;
    case 44: snprintf(buf, sizeof(buf), "mem_write16(s,%s,(u16)%s);", ea_d().c_str(), RS.c_str()); return buf;
    case 45: snprintf(buf, sizeof(buf), "mem_write16(s,%s,(u16)%s); %s = %s+(s32)%d;", ea_d().c_str(), RS.c_str(), RA.c_str(), RA.c_str(), imm); return buf;
    case 46: { // lmw
        std::string s2;
        for (u32 r = I.RD; r < 32; r++) {
            char t[80]; snprintf(t, sizeof(t), "%s = mem_read32(s,%s+(s32)%d+(%u-%u)*4); ",
                gpr(r).c_str(), RA.c_str(), imm, r, I.RD);
            s2 += t;
        }
        return s2;
    }
    case 47: { // stmw
        std::string s2;
        for (u32 r = I.RS; r < 32; r++) {
            char t[80]; snprintf(t, sizeof(t), "mem_write32(s,%s+(s32)%d+(%u-%u)*4,%s); ",
                RA.c_str(), imm, r, I.RS, gpr(r).c_str());
            s2 += t;
        }
        return s2;
    }
    case 48: { // lfs
        snprintf(buf, sizeof(buf), "{ u32 _v=mem_read32(s,%s); float _f; __builtin_memcpy(&_f,&_v,4); %s = (double)_f; }",
            ea_d().c_str(), fpr_d(I.FD).c_str()); return buf;
    }
    case 49: { // lfsu (load float single + update RA)
        snprintf(buf, sizeof(buf), "{ u32 _ea=%s+(s32)%d; u32 _v=mem_read32(s,_ea); float _f; __builtin_memcpy(&_f,&_v,4); %s=(double)_f; %s=_ea; }",
            gpr(I.RA).c_str(), imm, fpr_d(I.FD).c_str(), gpr(I.RA).c_str()); return buf;
    }
    case 50: { // lfd
        snprintf(buf, sizeof(buf), "{ u64 _v=mem_read64(s,%s); __builtin_memcpy(&%s,&_v,8); }",
            ea_d().c_str(), fpr_d(I.FD).c_str()); return buf;
    }
    case 51: { // lfdu (load float double + update RA)
        snprintf(buf, sizeof(buf), "{ u32 _ea=%s+(s32)%d; u64 _v=mem_read64(s,_ea); __builtin_memcpy(&%s,&_v,8); %s=_ea; }",
            gpr(I.RA).c_str(), imm, fpr_d(I.FD).c_str(), gpr(I.RA).c_str()); return buf;
    }
    case 52: { // stfs
        snprintf(buf, sizeof(buf), "{ float _f=(float)%s; u32 _v; __builtin_memcpy(&_v,&_f,4); mem_write32(s,%s,_v); }",
            fpr_d(I.FD).c_str(), ea_d().c_str()); return buf;
    }
    case 53: { // stfsu (store float single + update RA)
        snprintf(buf, sizeof(buf), "{ u32 _ea=%s+(s32)%d; float _f=(float)%s; u32 _v; __builtin_memcpy(&_v,&_f,4); mem_write32(s,_ea,_v); %s=_ea; }",
            gpr(I.RA).c_str(), imm, fpr_d(I.FD).c_str(), gpr(I.RA).c_str()); return buf;
    }
    case 54: { // stfd
        snprintf(buf, sizeof(buf), "{ u64 _v; __builtin_memcpy(&_v,&%s,8); mem_write64(s,%s,_v); }",
            fpr_d(I.FD).c_str(), ea_d().c_str()); return buf;
    }
    case 55: { // stfdu (store float double + update RA)
        snprintf(buf, sizeof(buf), "{ u32 _ea=%s+(s32)%d; u64 _v; __builtin_memcpy(&_v,&%s,8); mem_write64(s,_ea,_v); %s=_ea; }",
            gpr(I.RA).c_str(), imm, fpr_d(I.FD).c_str(), gpr(I.RA).c_str()); return buf;
    }
    case 31: { // X-form loads/stores
        u32 xop = I.SUBOP10;
        switch (xop) {
        case 23:  snprintf(buf, sizeof(buf), "%s = mem_read32(s,%s);", RD.c_str(), ea_x().c_str()); return buf;
        case 87:  snprintf(buf, sizeof(buf), "%s = mem_read8(s,%s);", RD.c_str(), ea_x().c_str()); return buf;
        case 279: snprintf(buf, sizeof(buf), "%s = mem_read16(s,%s);", RD.c_str(), ea_x().c_str()); return buf;
        case 343: snprintf(buf, sizeof(buf), "%s = (u32)(s32)(s16)mem_read16(s,%s);", RD.c_str(), ea_x().c_str()); return buf;
        case 151: snprintf(buf, sizeof(buf), "mem_write32(s,%s,%s);", ea_x().c_str(), RS.c_str()); return buf;
        case 215: snprintf(buf, sizeof(buf), "mem_write8(s,%s,(u8)%s);", ea_x().c_str(), RS.c_str()); return buf;
        case 407: snprintf(buf, sizeof(buf), "mem_write16(s,%s,(u16)%s);", ea_x().c_str(), RS.c_str()); return buf;
        case 55:  // lwzux (load word + update)
            snprintf(buf, sizeof(buf), "{ u32 _ea=%s+%s; %s=mem_read32(s,_ea); %s=_ea; }", RA.c_str(), RB.c_str(), RD.c_str(), RA.c_str()); return buf;
        case 119: // lbzux
            snprintf(buf, sizeof(buf), "{ u32 _ea=%s+%s; %s=mem_read8(s,_ea); %s=_ea; }", RA.c_str(), RB.c_str(), RD.c_str(), RA.c_str()); return buf;
        case 311: // lhzux
            snprintf(buf, sizeof(buf), "{ u32 _ea=%s+%s; %s=mem_read16(s,_ea); %s=_ea; }", RA.c_str(), RB.c_str(), RD.c_str(), RA.c_str()); return buf;
        case 375: // lhaux
            snprintf(buf, sizeof(buf), "{ u32 _ea=%s+%s; %s=(u32)(s32)(s16)mem_read16(s,_ea); %s=_ea; }", RA.c_str(), RB.c_str(), RD.c_str(), RA.c_str()); return buf;
        case 183: // stwux
            snprintf(buf, sizeof(buf), "{ u32 _ea=%s+%s; mem_write32(s,_ea,%s); %s=_ea; }", RA.c_str(), RB.c_str(), RS.c_str(), RA.c_str()); return buf;
        case 247: // stbux
            snprintf(buf, sizeof(buf), "{ u32 _ea=%s+%s; mem_write8(s,_ea,(u8)%s); %s=_ea; }", RA.c_str(), RB.c_str(), RS.c_str(), RA.c_str()); return buf;
        case 439: // sthux
            snprintf(buf, sizeof(buf), "{ u32 _ea=%s+%s; mem_write16(s,_ea,(u16)%s); %s=_ea; }", RA.c_str(), RB.c_str(), RS.c_str(), RA.c_str()); return buf;
        case 535: // lfsx
            snprintf(buf, sizeof(buf), "{ u32 _v=mem_read32(s,%s); float _f; __builtin_memcpy(&_f,&_v,4); %s=(double)_f; }", ea_x().c_str(), fpr_d(I.FD).c_str()); return buf;
        case 567: // lfsux
            snprintf(buf, sizeof(buf), "{ u32 _ea=%s+%s; u32 _v=mem_read32(s,_ea); float _f; __builtin_memcpy(&_f,&_v,4); %s=(double)_f; %s=_ea; }", RA.c_str(), RB.c_str(), fpr_d(I.FD).c_str(), RA.c_str()); return buf;
        case 599: // lfdx
            snprintf(buf, sizeof(buf), "{ u64 _v=mem_read64(s,%s); __builtin_memcpy(&%s,&_v,8); }", ea_x().c_str(), fpr_d(I.FD).c_str()); return buf;
        case 631: // lfdux
            snprintf(buf, sizeof(buf), "{ u32 _ea=%s+%s; u64 _v=mem_read64(s,_ea); __builtin_memcpy(&%s,&_v,8); %s=_ea; }", RA.c_str(), RB.c_str(), fpr_d(I.FD).c_str(), RA.c_str()); return buf;
        case 663: // stfsx
            snprintf(buf, sizeof(buf), "{ float _f=(float)%s; u32 _v; __builtin_memcpy(&_v,&_f,4); mem_write32(s,%s,_v); }", fpr_d(I.FD).c_str(), ea_x().c_str()); return buf;
        case 695: // stfsux
            snprintf(buf, sizeof(buf), "{ u32 _ea=%s+%s; float _f=(float)%s; u32 _v; __builtin_memcpy(&_v,&_f,4); mem_write32(s,_ea,_v); %s=_ea; }", RA.c_str(), RB.c_str(), fpr_d(I.FD).c_str(), RA.c_str()); return buf;
        case 727: // stfdx
            snprintf(buf, sizeof(buf), "{ u64 _v; __builtin_memcpy(&_v,&%s,8); mem_write64(s,%s,_v); }", fpr_d(I.FD).c_str(), ea_x().c_str()); return buf;
        case 759: // stfdux
            snprintf(buf, sizeof(buf), "{ u32 _ea=%s+%s; u64 _v; __builtin_memcpy(&_v,&%s,8); mem_write64(s,_ea,_v); %s=_ea; }", RA.c_str(), RB.c_str(), fpr_d(I.FD).c_str(), RA.c_str()); return buf;
        case 983: // stfiwx (store float as integer word)
            snprintf(buf, sizeof(buf), "{ u32 _v; __builtin_memcpy(&_v,&%s,4); mem_write32(s,%s,_v); }", fpr_d(I.FD).c_str(), ea_x().c_str()); return buf;
        case 534: // lwbrx
            snprintf(buf, sizeof(buf), "%s = BSWAP32(mem_read32(s,%s));", RD.c_str(), ea_x().c_str()); return buf;
        case 790: // lhbrx
            snprintf(buf, sizeof(buf), "%s = BSWAP16(mem_read16(s,%s));", RD.c_str(), ea_x().c_str()); return buf;
        case 662: // stwbrx
            snprintf(buf, sizeof(buf), "mem_write32(s,%s,BSWAP32(%s));", ea_x().c_str(), RS.c_str()); return buf;
        case 1014: // dcbz
            snprintf(buf, sizeof(buf), "{ u32 _a=(%s+%s)&~31u; for(int _i=0;_i<32;_i++) mem_write8(s,_a+_i,0); }",
                RA.c_str(), RB.c_str()); return buf;
        default:
            snprintf(buf, sizeof(buf), "/* x-ldst xop=%u */", xop); return buf;
        }
    }
    default:
        snprintf(buf, sizeof(buf), "/* ldst op=%u */", op); return buf;
    }
}

// ============================================================
// Floating-point
// ============================================================
std::string CBackend::emit_float(const DecodedInstr& d) {
    char buf[512];
    const auto& I = d.raw;
    u32 op = I.OPCD;
    std::string FD = fpr_d(I.FD), FA = fpr_d(I.RA), FB = fpr_d(I.RB), FC = fpr_d(I.SUBOP5);
    // Note: for op 59/63 field RC is actually FC (5-bit src C register = SUBOP5 bits 6-10)
    // Dolphin's Gekko.h: for 5-bit opcode forms, RC field = bits 6-10 of the instruction
    // For simplicity we use I.SUBOP5 as FC register index
    u32 fc_reg = (I.hex >> 6) & 0x1F;  // actual RC field position
    std::string FC2 = fpr_d(fc_reg);
    bool rc = I.Rc;

    auto fpscr_update = [&]() -> std::string {
        return rc ? " /* fpscr CR1 update omitted */" : "";
        };

    if (op == 59 || op == 63) {
        u32 xop5 = (I.hex >> 1) & 0x1F; // 5-bit sub-opcode
        switch (xop5) {
        case 18: snprintf(buf, sizeof(buf), "%s = %s / %s;%s", FD.c_str(), FA.c_str(), FB.c_str(), fpscr_update().c_str()); return buf;
        case 20: snprintf(buf, sizeof(buf), "%s = %s - %s;%s", FD.c_str(), FA.c_str(), FB.c_str(), fpscr_update().c_str()); return buf;
        case 21: snprintf(buf, sizeof(buf), "%s = %s + %s;%s", FD.c_str(), FA.c_str(), FB.c_str(), fpscr_update().c_str()); return buf;
        case 22: snprintf(buf, sizeof(buf), "%s = sqrt(%s);%s", FD.c_str(), FB.c_str(), fpscr_update().c_str()); return buf;
        case 25: // fmul
            if (op == 59) snprintf(buf, sizeof(buf), "%s = (double)((float)%s * (float)%s);%s", FD.c_str(), FA.c_str(), FC2.c_str(), fpscr_update().c_str());
            else          snprintf(buf, sizeof(buf), "%s = %s * %s;%s", FD.c_str(), FA.c_str(), FC2.c_str(), fpscr_update().c_str());
            return buf;
        case 28: // fmsub
            snprintf(buf, sizeof(buf), "%s = fma(%s,%s,-%s);%s", FD.c_str(), FA.c_str(), FC2.c_str(), FB.c_str(), fpscr_update().c_str()); return buf;
        case 29: // fmadd
            snprintf(buf, sizeof(buf), "%s = fma(%s,%s,%s);%s", FD.c_str(), FA.c_str(), FC2.c_str(), FB.c_str(), fpscr_update().c_str()); return buf;
        case 30: // fnmsub
            snprintf(buf, sizeof(buf), "%s = -fma(%s,%s,-%s);%s", FD.c_str(), FA.c_str(), FC2.c_str(), FB.c_str(), fpscr_update().c_str()); return buf;
        case 31: // fnmadd
            snprintf(buf, sizeof(buf), "%s = -fma(%s,%s,%s);%s", FD.c_str(), FA.c_str(), FC2.c_str(), FB.c_str(), fpscr_update().c_str()); return buf;
        }
    }
    // 10-bit sub-opcode forms
    u32 xop = I.SUBOP10;
    if (op == 63) {
        switch (xop) {
        case 0:  // fcmpu
        case 32: // fcmpo
            snprintf(buf, sizeof(buf), "{ int _l=%s<%s,_g=%s>%s,_e=%s==%s; cr_set_field(s,%u,_l,_g,_e,0); }",
                FA.c_str(), FB.c_str(), FA.c_str(), FB.c_str(), FA.c_str(), FB.c_str(), I.CRFD);
            return buf;
        case 12: // frsp
            snprintf(buf, sizeof(buf), "%s = (double)(float)%s;%s", FD.c_str(), FB.c_str(), fpscr_update().c_str()); return buf;
        case 14: // fctiw
            snprintf(buf, sizeof(buf), "{ s32 _v=(s32)%s; double _d; __builtin_memcpy(&_d,&_v,4); %s=_d; }", FB.c_str(), FD.c_str()); return buf;
        case 15: // fctiwz
            snprintf(buf, sizeof(buf), "{ s32 _v=(s32)%s; double _d; __builtin_memcpy(&_d,&_v,4); %s=_d; }", FB.c_str(), FD.c_str()); return buf;
        case 40: snprintf(buf, sizeof(buf), "%s = -%s;%s", FD.c_str(), FB.c_str(), fpscr_update().c_str()); return buf; // fneg
        case 72: snprintf(buf, sizeof(buf), "%s = %s;%s", FD.c_str(), FB.c_str(), fpscr_update().c_str()); return buf; // fmr
        case 136: snprintf(buf, sizeof(buf), "%s = -fabs(%s);%s", FD.c_str(), FB.c_str(), fpscr_update().c_str()); return buf; // fnabs: force negative
        case 264: snprintf(buf, sizeof(buf), "%s = fabs(%s);%s", FD.c_str(), FB.c_str(), fpscr_update().c_str()); return buf; // fabs
        }
    }
    snprintf(buf, sizeof(buf), "/* fp %s unlifted */", d.mnemonic.c_str());
    return buf;
}

// ============================================================
// System / SPR instructions
// ============================================================
std::string CBackend::emit_system(const DecodedInstr& d) {
    char buf[256];
    const auto& I = d.raw;
    if (d.mnemonic == "sc")    return "rt_syscall(s);";
    if (d.mnemonic == "rfi")   return "goto _fn_return; /* rfi */";
    if (d.mnemonic == "sync")  return "/* sync */";
    if (d.mnemonic == "eieio") return "/* eieio */";
    if (d.mnemonic == "isync") return "/* isync */";
    if (d.mnemonic == "mfmsr") { snprintf(buf, sizeof(buf), "%s = 0; /* mfmsr stub */", gpr(I.RD).c_str()); return buf; }
    if (d.mnemonic == "mtmsr") return "/* mtmsr stub */";
    if (d.mnemonic == "mftb") {
        switch (I.SPR()) {
        case 268: snprintf(buf, sizeof(buf), "%s = rt_read_tbl(s);", gpr(I.RD).c_str()); return buf;
        case 269: snprintf(buf, sizeof(buf), "%s = rt_read_tbu(s);", gpr(I.RD).c_str()); return buf;
        default:  snprintf(buf, sizeof(buf), "%s = 0; /* mftb %u */", gpr(I.RD).c_str(), I.SPR()); return buf;
        }
    }
    snprintf(buf, sizeof(buf), "/* sys: %s */", d.mnemonic.c_str());
    return buf;
}

// ============================================================
// Paired-single (GC-specific SIMD)
// ============================================================
std::string CBackend::emit_ps(const DecodedInstr& d) {
    char buf[512];
    const auto& I = d.raw;
    u32 op = I.OPCD;
    u32 xop5 = (I.hex >> 1) & 0x1F;
    // ps registers hold two f32 values in ps0 and ps1
    auto ps0 = [](u32 r) { char b[32]; snprintf(b, sizeof(b), "s->fpr[%u].ps0", r); return std::string(b); };
    auto ps1 = [](u32 r) { char b[32]; snprintf(b, sizeof(b), "s->fpr[%u].ps1", r); return std::string(b); };
    u32 FD = I.FD, FA = I.RA, FB = I.RB_5, FC = (I.hex >> 6) & 0x1F;

    // Load/store paired-single
    if (op == 56 || op == 57) { // psq_l / psq_lu
        snprintf(buf, sizeof(buf), "{ /* psq_l stub */ }"); return buf;
    }
    if (op == 60 || op == 61) { // psq_st / psq_stu
        snprintf(buf, sizeof(buf), "{ /* psq_st stub */ }"); return buf;
    }

    if (op == 4) {
        switch (xop5) {
        case 18: // ps_div
            snprintf(buf, sizeof(buf), "%s=%s/%s; %s=%s/%s;",
                ps0(FD).c_str(), ps0(FA).c_str(), ps0(FB).c_str(),
                ps1(FD).c_str(), ps1(FA).c_str(), ps1(FB).c_str()); return buf;
        case 20: // ps_sub
            snprintf(buf, sizeof(buf), "%s=%s-%s; %s=%s-%s;",
                ps0(FD).c_str(), ps0(FA).c_str(), ps0(FB).c_str(),
                ps1(FD).c_str(), ps1(FA).c_str(), ps1(FB).c_str()); return buf;
        case 21: // ps_add
            snprintf(buf, sizeof(buf), "%s=%s+%s; %s=%s+%s;",
                ps0(FD).c_str(), ps0(FA).c_str(), ps0(FB).c_str(),
                ps1(FD).c_str(), ps1(FA).c_str(), ps1(FB).c_str()); return buf;
        case 25: // ps_mul
            snprintf(buf, sizeof(buf), "%s=%s*%s; %s=%s*%s;",
                ps0(FD).c_str(), ps0(FA).c_str(), ps0(FC).c_str(),
                ps1(FD).c_str(), ps1(FA).c_str(), ps1(FC).c_str()); return buf;
        case 29: // ps_madd
            snprintf(buf, sizeof(buf), "%s=fmaf(%s,%s,%s); %s=fmaf(%s,%s,%s);",
                ps0(FD).c_str(), ps0(FA).c_str(), ps0(FC).c_str(), ps0(FB).c_str(),
                ps1(FD).c_str(), ps1(FA).c_str(), ps1(FC).c_str(), ps1(FB).c_str()); return buf;
        }
        // 10-bit xop
        u32 xop = I.SUBOP10;
        switch (xop) {
        case 40: // ps_neg
            snprintf(buf, sizeof(buf), "%s=-%s; %s=-%s;",
                ps0(FD).c_str(), ps0(FB).c_str(), ps1(FD).c_str(), ps1(FB).c_str()); return buf;
        case 72: // ps_mr
            snprintf(buf, sizeof(buf), "%s=%s; %s=%s;",
                ps0(FD).c_str(), ps0(FB).c_str(), ps1(FD).c_str(), ps1(FB).c_str()); return buf;
        case 264: // ps_abs
            snprintf(buf, sizeof(buf), "%s=fabsf(%s); %s=fabsf(%s);",
                ps0(FD).c_str(), ps0(FB).c_str(), ps1(FD).c_str(), ps1(FB).c_str()); return buf;
        case 528: // ps_merge00
            snprintf(buf, sizeof(buf), "%s=%s; %s=%s;",
                ps0(FD).c_str(), ps0(FA).c_str(), ps1(FD).c_str(), ps0(FB).c_str()); return buf;
        case 560: // ps_merge01
            snprintf(buf, sizeof(buf), "%s=%s; %s=%s;",
                ps0(FD).c_str(), ps0(FA).c_str(), ps1(FD).c_str(), ps1(FB).c_str()); return buf;
        case 592: // ps_merge10
            snprintf(buf, sizeof(buf), "%s=%s; %s=%s;",
                ps0(FD).c_str(), ps1(FA).c_str(), ps1(FD).c_str(), ps0(FB).c_str()); return buf;
        case 624: // ps_merge11
            snprintf(buf, sizeof(buf), "%s=%s; %s=%s;",
                ps0(FD).c_str(), ps1(FA).c_str(), ps1(FD).c_str(), ps1(FB).c_str()); return buf;
        }
    }
    snprintf(buf, sizeof(buf), "/* ps: %s */", d.mnemonic.c_str());
    return buf;
}

// ============================================================
// Dispatch table
// ============================================================
std::string CBackend::emit_dispatch_table(const std::map<u32, Function>& functions) {
    std::ostringstream out;
    out << "/* Dispatch table: guest address → translated function */\n";
    out << "#include <stdint.h>\n";
    out << "typedef void (*TranslatedFn)(struct PPCState*);\n";
    out << "struct DispatchEntry { uint32_t guest_addr; TranslatedFn fn; };\n\n";

    // Forward-declare all functions
    out << "/* Forward declarations */\n";
    for (const auto& [addr, fn] : functions)
        out << "static " << fn_proto(fn) << ";\n";
    out << "\n";

    out << "static const struct DispatchEntry kDispatchTable[] = {\n";
    for (const auto& [addr, fn] : functions) {
        char line[128];
        snprintf(line, sizeof(line), "  { 0x%08xu, %s },\n", addr, fn.name.c_str());
        out << line;
    }
    out << "};\n";
    out << "static const int kDispatchTableSize = "
        << functions.size() << ";\n";

    // Binary search helper
    out << R"(
static TranslatedFn dispatch_lookup(uint32_t guest_addr) {
    int lo = 0, hi = kDispatchTableSize - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        if (kDispatchTable[mid].guest_addr == guest_addr) return kDispatchTable[mid].fn;
        if (kDispatchTable[mid].guest_addr < guest_addr) lo = mid + 1;
        else hi = mid - 1;
    }
    return NULL;
}
)";
    return out.str();
}
